### ISSUE TITLE
labeling boxplots with tukey test results

### ISSUE THREAD

**Issue by pestack** [USGS-R/hypeRusgs#13]

**Comment by pestack** [comment]
[TukeyBoxPlotsTestv5.zip](https://github.com/USGS-R/hypeRusgs/files/2669429/TukeyBoxPlotsTestv5.zip)

**Comment by lindsayplatt** [comment]
Covered in the 12-12-2018 webinar. See https://github.com/USGS-R/hypeRusgs/blob/master/Webinar-12-12-2018/TukeyBoxPlotsTestv5.R
