### ISSUE TITLE
Working with spatial data and mapping in R

### ISSUE THREAD

**Issue by ldesm** [USGS-R/hypeRusgs#15]

**Comment by lindsayplatt** [comment]
Thanks for the idea! Any specific applications? Creating maps for publication, or doing more GIS-like analyses? Do you have specific shapefiles or spatial data you would like to map?

**Comment by ldesm** [comment]
All of the above!

Spatial data input/output in R, basic data manipulation (subsetting,
appending data, editing data points and attributes), map visualization for
report figures & presentations, well as more complex GIS type analysis
(overlay--for example)--I think all these things would of general interest.
I don't know how much people know about R's spatial capabilities, it was
new to me and might be to others as well, even though they may have used R
for a while. Also, being able to review model input data and model output
while doing analysis, rather than having to open up ArcMap and bring the
data back into that environment to see it, would save a lot of time.

But specifically, there are a couple of things I've been trying to do,
unsuccessfully:

--write a shape file (or any format file) from R that can be read into and
used in ArcGIS. I can ESRI shapefiles and geodatabase files into R, work
with them and plot them, but have not been able to produce files that will
get back into Arc. So, spatial data formats and inter-compatability with
ESRI Arc software would be a topic I would be interested in, and maybe
others as well

-- view statistical model output in R. The output are predicted values for
each point in a large grid file (~195000 points or polygons), I've been
trying to join the predicted values to a shape file and plot it in R, but
it just doesn't work. Maybe the file is too large? Perhaps file size is a
limitation in R.

Thanks so much for all these training sessions, they are awesome!

Leslie

Leslie A. DeSimone
U.S. Geological Survey
New England Water Science Center
10 Bearfoot Road
Northborough, MA 01532
508-490-5023

ldesimon@usgs.gov

**Comment by lindsayplatt** [comment]
Closed by #22
