### ISSUE TITLE
getmap() and new googlemap API requirements for ggmap

### ISSUE THREAD

**Issue by crosecrans-usgs** [USGS-R/hypeRusgs#20]
Just curious if there exists a workaround googles new requirement of us to generate an API and set up billing to use their services, when using getmap() function in ggmap. See step 5 in link below:

https://www.littlemissdata.com/blog/maps 

I don't believe DOI uses google cloud platform, which I believe would require us to use our personal google accounts and billing to obtain an API. I was hoping not to have to do that.  One thought I had was to export the a google map as an .rds file ( I have done this in the past and saved maps to a directory so I could use them offline, but this was of course before google started setting restrictions. Any suggestions or help is much appreciated).

**Comment by lindsayplatt** [comment]
Closed by #22
