### ISSUE TITLE
Creating SPN-compliant plots

### ISSUE THREAD

**Issue by lindsayplatt** [USGS-R/hypeRusgs#24]
Please comment below with some of the more challenging style requirements and I can try to put a few examples accomplishing those together for the webinar on 5/29.

**Comment by kransom14** [comment]
Superscripts, subscripts, and special characters for units (such as for degrees) in labels, and positioning labels.

**Comment by jakingsb** [comment]
These may or may not be challenging:
X-Y plots--Tick marks inside the axes; how to specify interval for major and minor tick marks.

**Comment by mlperickson** [comment]
Adding counts to box plots, formatting and positioning the count. Formatting the 'explanation' of a box plot.

**Comment by lindsayplatt** [comment]
@mlperickson I will defer to this blog post which is the master of all things boxplots for us https://waterdata.usgs.gov/blog/boxplots/. I highly recommend following along with that. Also, I have some code in the `Webinar-12-12-2018` folder that goes over using the code from the blog.
