### ISSUE TITLE
combining multiple ecdf plots in ggplot

### ISSUE THREAD

**Issue by crosecrans-usgs** [USGS-R/hypeRusgs#29]
This seems simple enough, but it appears combining multiple ecdf plots in ggplot does not use my usual method of adding layers to plots from multiple data sources.....likely due to the stat function using a different format for adding multiple plots that I could not figure out.  Don't really need this one discussed in our R training group if we don't have time, just looking for the correct formatting.
[ecdf_wtf.zip](https://github.com/USGS-R/hypeRusgs/files/3428749/ecdf_wtf.zip)

**Comment by lindsayplatt** [comment]
You just need the data in long format:

```r
library(tidyr) # for gather
library(ggplot2)

vals_transformed <- gather(vals, key = 'ecdf_type', value = value, -R00950)
ggplot(data = vals_transformed, 
       aes(log(value), color = ecdf_type))+
  stat_ecdf(geom="point") + 
  scale_color_manual(values=c("orange", "black", "brown"))
```

Result:
![image](https://user-images.githubusercontent.com/13220910/62219817-9cd08400-b374-11e9-8ce3-83329b00a1ef.png)
